---
layout: posts
title: "[Java] Java 01"
date:  2019-07-22 09:26:55 +0900
categories:
    - Java
---
//	예외가 발생하면
				//	자바 런처 :  예외다!!
				//	new IndexOutOfBoundsException();

                ArithmeticException e) {	//	0으로 나누었을때 발생

                IndexOutOfBoundsException e) {	//	배열의 크기가 3으로 고정되어 있기 때문에 그 이상 값을 넣으면 발생

                //	커스텀 예외

                class TestException extends Exception {
	public TestException() {
		super("오류");
	}
}



/*
 * 예외 처리
 * try {..}	: 예외 발생 영역을 블록으로 지정
 * catch(e) {..}	: try에서 발생된 예외 객체를 잡는다.
 */

import java.util.InputMismatchException;
import java.util.Scanner;

public class Main {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		int n1 = 0;
		int n2 = 0;
		int ret = 0;
		
		try {
			System.out.println("수 입력 : ");
			n1 = sc.nextInt();
			//	if(숫자가 아닌 문자가 입력된 경우) {
			//		throw new InputMismathException();
			//	}
			//	와 비슷한 원리
			System.out.println("수 입력 : ");
			n2 = sc.nextInt();
			ret = n1 / n2;
			System.out.println("결과 : " + ret);
		} catch(InputMismatchException e) {
			System.out.println("입력 오류");
			e.printStackTrace();
			//	메소드 스택을 역행하면서 에러시점을 출력한다.
		} catch (ArithmeticException e) {
			System.out.println("나눗셈 오류");
		} finally {
			System.out.println("이 부분은 try의 결과와 관계없이 블록이 끝나면 무조건 호출된다.");
			//	입출력 스트림을 닫는 용도로 많이 사용
			//	예외와 관련되어 실행되어야 하는 코드를 쓴다.
		}
		
		sc.close();




        /*
 * 커스텀 Exception
 * 관리를 위해 직접 만들 수 있다.
 * throw : 예외 객체를 던지는 구문
 * 
 */
class MyException extends Exception {
	public MyException(String m) {
		super(m);
	}
}






/*
 * throws : 예외를 해당 함수를 호출한곳으로 넘겨줌(함수 정의시 사용)
 public static int scan() throws MyException {
		int kor = Integer.parseInt(sc.nextLine());
		if (kor < 0 || kor > 100) {
			throw new MyException("값이 범위를 벗어남");
		}
		return kor;
	}
 */



 /*
 * RuntimeException : 런타임시에 발생하는것 = 컴파일시에는 발생하지 않는다는 의미
 * 이런경우 try catch문을 호출장소에서 사용하지 않아도 된다.
 */